INSERT INTO film (titre, realisateur, date_sortie, genre) VALUES
    ('Inception', 'Christopher Nolan', '2010-07-21', 'SCIENCE_FICTION'),
    ('Le Fabuleux Destin d''Amélie Poulain', 'Jean-Pierre Jeunet', '2001-04-25', 'COMEDIE'),
    ('Intouchables', 'Olivier Nakache', '2011-11-02', 'COMEDIE_DRAMATIQUE'),
    ('The Godfather', 'Francis Ford Coppola', '1972-10-18', 'CRIME'),
    ('Interstellar', 'Christopher Nolan', '2014-11-05', 'SCIENCE_FICTION'),
    ('The Dark Knight', 'Christopher Nolan', '2008-08-13', 'SUPER_HEROS'),
    ('Oppenheimer', 'Christopher Nolan', '2023-07-19', 'BIOPIC'),
    ('The Prestige', 'Christopher Nolan', '2006-11-15', 'MYSTERE'),
    ('Memento', 'Christopher Nolan', '2000-10-11', 'THRILLER'),
    ('Dunkirk', 'Christopher Nolan', '2017-07-19', 'GUERRE'),
    ('Titanic', 'James Cameron', '1998-01-07', 'ROMANCE'),
    ('Pulp Fiction', 'Quentin Tarantino', '1994-10-26', 'CRIME'),
    ('Forrest Gump', 'Robert Zemeckis', '1994-10-05', 'DRAME'),
    ('The Matrix', 'Lana Wachowski', '1999-06-23', 'SCIENCE_FICTION'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', '2001-12-19', 'FANTASTIQUE'),
    ('Gladiator', 'Ridley Scott', '2000-06-20', 'HISTORIQUE'),
    ('Joker', 'Todd Phillips', '2019-10-09', 'DRAME'),
    ('Alien', 'Ridley Scott', '1979-09-12', 'HORREUR'),
    ('Blade Runner', 'Ridley Scott', '1982-09-15', 'SCIENCE_FICTION'),
    ('Back to the Future', 'Robert Zemeckis', '1985-10-30', 'SCIENCE_FICTION'),
    ('The Silence of the Lambs', 'Jonathan Demme', '1991-04-10', 'THRILLER'),
    ('Fight Club', 'David Fincher', '1999-11-10', 'DRAME'),
    ('Seven', 'David Fincher', '1996-01-31', 'POLICIER'),
    ('La Haine', 'Mathieu Kassovitz', '1995-05-31', 'DRAME'),
    ('Le Dîner de cons', 'Francis Veber', '1998-04-15', 'COMEDIE'),
    ('Les Visiteurs', 'Jean-Marie Poiré', '1993-01-27', 'COMEDIE'),
    ('Léon', 'Luc Besson', '1994-09-14', 'ACTION'),
    ('Le Grand Bleu', 'Luc Besson', '1988-05-11', 'DRAME'),
    ('The Lion King', 'Roger Allers', '1994-11-09', 'ANIMATION'),
    ('Toy Story', 'John Lasseter', '1996-03-27', 'ANIMATION'),
    ('Le Voyage de Chihiro', 'Hayao Miyazaki', '2002-04-10', 'ANIMATION'),
    ('Avengers: Endgame', 'Anthony Russo', '2019-04-24', 'SUPER_HEROS'),
    ('Il était une fois dans l''Ouest', 'Sergio Leone', '1969-08-27', 'WESTERN'),
    ('Le Bon, la Brute et le Truand', 'Sergio Leone', '1968-03-08', 'WESTERN'),
    ('Mission: Impossible', 'Brian De Palma', '1996-10-30', 'ESPIONNAGE'),
    ('Casino Royale', 'Martin Campbell', '2006-11-22', 'ESPIONNAGE'),
    ('Top Gun: Maverick', 'Joseph Kosinski', '2022-05-25', 'ACTION'),
    ('Rocky', 'John G. Avildsen', '1977-03-30', 'SPORT'),
    ('La La Land', 'Damien Chazelle', '2017-01-25', 'COMEDIE_MUSICALE'),
    ('Whiplash', 'Damien Chazelle', '2014-12-24', 'MUSICAL'),
    ('Mamma Mia!', 'Phyllida Lloyd', '2008-09-10', 'COMEDIE_MUSICALE'),
    ('Saving Private Ryan', 'Steven Spielberg', '1998-09-30', 'GUERRE'),
    ('Jurassic Park', 'Steven Spielberg', '1993-10-20', 'AVENTURE'),
    ('Raiders of the Lost Ark', 'Steven Spielberg', '1981-09-16', 'AVENTURE'),
    ('Star Wars: A New Hope', 'George Lucas', '1977-10-19', 'SCIENCE_FICTION'),
    ('Parasite', 'Bong Joon-ho', '2019-06-05', 'THRILLER'),
    ('Dune', 'Denis Villeneuve', '2021-09-15', 'SCIENCE_FICTION'),
    ('The Shawshank Redemption', 'Frank Darabont', '1995-03-01', 'DRAME'),
    ('Bienvenue chez les Ch''tis', 'Dany Boon', '2008-02-27', 'COMEDIE'),
    ('The Shining', 'Stanley Kubrick', '1980-10-16', 'HORREUR'),
    ('Bohemian Rhapsody', 'Bryan Singer', '2018-10-31', 'BIOPIC'),
    ('La Marche de l''empereur', 'Luc Jacquet', '2005-01-26', 'DOCUMENTAIRE'),
    ('The Devil Wears Prada', 'David Frankel', '2006-09-27', 'COMEDIE'),
    ('The Wolf of Wall Street', 'Martin Scorsese', '2013-12-25', 'BIOPIC'),
    ('Goodfellas', 'Martin Scorsese', '1990-09-12', 'CRIME'),
    ('Taxi Driver', 'Martin Scorsese', '1976-06-02', 'DRAME'),
    ('Paddington', 'Paul King', '2014-12-03', 'FAMILLE');

INSERT INTO acteur (nom, prenom) VALUES
    ('DiCaprio', 'Leonardo'),
    ('Tautou', 'Audrey'),
    ('Cluzet', 'François'),
    ('Sy', 'Omar'),
    ('Brando', 'Marlon'),
    ('Pacino', 'Al'),
    ('McConaughey', 'Matthew'),
    ('Gordon-Levitt', 'Joseph'),
    ('Cotillard', 'Marion'),
    ('Page', 'Elliot'),
    ('Hardy', 'Tom'),
    ('Hathaway', 'Anne'),
    ('Chastain', 'Jessica'),
    ('Bale', 'Christian'),
    ('Ledger', 'Heath'),
    ('Oldman', 'Gary'),
    ('Murphy', 'Cillian'),
    ('Blunt', 'Emily'),
    ('Damon', 'Matt'),
    ('Jackman', 'Hugh'),
    ('Johansson', 'Scarlett'),
    ('Pearce', 'Guy'),
    ('Styles', 'Harry'),
    ('Winslet', 'Kate'),
    ('Travolta', 'John'),
    ('Jackson', 'Samuel L.'),
    ('Thurman', 'Uma'),
    ('Hanks', 'Tom'),
    ('Wright', 'Robin'),
    ('Reeves', 'Keanu'),
    ('Fishburne', 'Laurence'),
    ('Moss', 'Carrie-Anne'),
    ('Wood', 'Elijah'),
    ('McKellen', 'Ian'),
    ('Mortensen', 'Viggo'),
    ('Crowe', 'Russell'),
    ('Phoenix', 'Joaquin'),
    ('Weaver', 'Sigourney'),
    ('Ford', 'Harrison'),
    ('Fox', 'Michael J.'),
    ('Lloyd', 'Christopher'),
    ('Foster', 'Jodie'),
    ('Hopkins', 'Anthony'),
    ('Pitt', 'Brad'),
    ('Norton', 'Edward'),
    ('Freeman', 'Morgan'),
    ('Cassel', 'Vincent'),
    ('Kassovitz', 'Mathieu'),
    ('Villeret', 'Jacques'),
    ('Lhermitte', 'Thierry'),
    ('Reno', 'Jean'),
    ('Clavier', 'Christian'),
    ('Portman', 'Natalie'),
    ('Barr', 'Jean-Marc'),
    ('Downey Jr.', 'Robert'),
    ('Evans', 'Chris'),
    ('Fonda', 'Henry'),
    ('Bronson', 'Charles'),
    ('Cardinale', 'Claudia'),
    ('Eastwood', 'Clint'),
    ('Cruise', 'Tom'),
    ('Craig', 'Daniel'),
    ('Green', 'Eva'),
    ('Stallone', 'Sylvester'),
    ('Gosling', 'Ryan'),
    ('Stone', 'Emma'),
    ('Teller', 'Miles'),
    ('Simmons', 'J.K.'),
    ('Streep', 'Meryl'),
    ('Neill', 'Sam'),
    ('Goldblum', 'Jeff'),
    ('Hamill', 'Mark'),
    ('Fisher', 'Carrie'),
    ('Song', 'Kang-ho'),
    ('Chalamet', 'Timothée'),
    ('Coleman', 'Zendaya'),
    ('Ferguson', 'Rebecca'),
    ('Robbins', 'Tim'),
    ('Boon', 'Dany'),
    ('Merad', 'Kad'),
    ('Nicholson', 'Jack'),
    ('Malek', 'Rami'),
    ('Robbie', 'Margot'),
    ('Hill', 'Jonah'),
    ('De Niro', 'Robert'),
    ('Liotta', 'Ray'),
    ('Pesci', 'Joe'),
    ('Whishaw', 'Ben');

INSERT INTO film_acteur (film_id, acteur_id)
SELECT f.id, a.id
FROM (VALUES
    ('Inception', 'DiCaprio'),
    ('Inception', 'Gordon-Levitt'),
    ('Inception', 'Cotillard'),
    ('Inception', 'Page'),
    ('Inception', 'Hardy'),
    ('Le Fabuleux Destin d''Amélie Poulain', 'Tautou'),
    ('Le Fabuleux Destin d''Amélie Poulain', 'Kassovitz'),
    ('Intouchables', 'Cluzet'),
    ('Intouchables', 'Sy'),
    ('The Godfather', 'Brando'),
    ('The Godfather', 'Pacino'),
    ('Interstellar', 'McConaughey'),
    ('Interstellar', 'Hathaway'),
    ('Interstellar', 'Chastain'),
    ('Interstellar', 'Damon'),
    ('The Dark Knight', 'Bale'),
    ('The Dark Knight', 'Ledger'),
    ('The Dark Knight', 'Oldman'),
    ('The Dark Knight', 'Freeman'),
    ('Oppenheimer', 'Murphy'),
    ('Oppenheimer', 'Blunt'),
    ('Oppenheimer', 'Damon'),
    ('The Prestige', 'Bale'),
    ('The Prestige', 'Jackman'),
    ('The Prestige', 'Johansson'),
    ('Memento', 'Pearce'),
    ('Memento', 'Moss'),
    ('Dunkirk', 'Hardy'),
    ('Dunkirk', 'Murphy'),
    ('Dunkirk', 'Styles'),
    ('Titanic', 'DiCaprio'),
    ('Titanic', 'Winslet'),
    ('Pulp Fiction', 'Travolta'),
    ('Pulp Fiction', 'Jackson'),
    ('Pulp Fiction', 'Thurman'),
    ('Forrest Gump', 'Hanks'),
    ('Forrest Gump', 'Wright'),
    ('The Matrix', 'Reeves'),
    ('The Matrix', 'Fishburne'),
    ('The Matrix', 'Moss'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'Wood'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'McKellen'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'Mortensen'),
    ('Gladiator', 'Crowe'),
    ('Gladiator', 'Phoenix'),
    ('Joker', 'Phoenix'),
    ('Alien', 'Weaver'),
    ('Blade Runner', 'Ford'),
    ('Back to the Future', 'Fox'),
    ('Back to the Future', 'Lloyd'),
    ('The Silence of the Lambs', 'Foster'),
    ('The Silence of the Lambs', 'Hopkins'),
    ('Fight Club', 'Pitt'),
    ('Fight Club', 'Norton'),
    ('Seven', 'Pitt'),
    ('Seven', 'Freeman'),
    ('La Haine', 'Cassel'),
    ('Le Dîner de cons', 'Villeret'),
    ('Le Dîner de cons', 'Lhermitte'),
    ('Les Visiteurs', 'Reno'),
    ('Les Visiteurs', 'Clavier'),
    ('Léon', 'Reno'),
    ('Léon', 'Portman'),
    ('Léon', 'Oldman'),
    ('Le Grand Bleu', 'Reno'),
    ('Le Grand Bleu', 'Barr'),
    ('Toy Story', 'Hanks'),
    ('Avengers: Endgame', 'Downey Jr.'),
    ('Avengers: Endgame', 'Evans'),
    ('Avengers: Endgame', 'Johansson'),
    ('Il était une fois dans l''Ouest', 'Fonda'),
    ('Il était une fois dans l''Ouest', 'Bronson'),
    ('Il était une fois dans l''Ouest', 'Cardinale'),
    ('Le Bon, la Brute et le Truand', 'Eastwood'),
    ('Mission: Impossible', 'Cruise'),
    ('Mission: Impossible', 'Reno'),
    ('Casino Royale', 'Craig'),
    ('Casino Royale', 'Green'),
    ('Top Gun: Maverick', 'Cruise'),
    ('Rocky', 'Stallone'),
    ('La La Land', 'Gosling'),
    ('La La Land', 'Stone'),
    ('Whiplash', 'Teller'),
    ('Whiplash', 'Simmons'),
    ('Mamma Mia!', 'Streep'),
    ('Saving Private Ryan', 'Hanks'),
    ('Saving Private Ryan', 'Damon'),
    ('Jurassic Park', 'Neill'),
    ('Jurassic Park', 'Goldblum'),
    ('Raiders of the Lost Ark', 'Ford'),
    ('Star Wars: A New Hope', 'Hamill'),
    ('Star Wars: A New Hope', 'Ford'),
    ('Star Wars: A New Hope', 'Fisher'),
    ('Parasite', 'Song'),
    ('Dune', 'Chalamet'),
    ('Dune', 'Coleman'),
    ('Dune', 'Ferguson'),
    ('The Shawshank Redemption', 'Robbins'),
    ('The Shawshank Redemption', 'Freeman'),
    ('Bienvenue chez les Ch''tis', 'Boon'),
    ('Bienvenue chez les Ch''tis', 'Merad'),
    ('The Shining', 'Nicholson'),
    ('Bohemian Rhapsody', 'Malek'),
    ('The Devil Wears Prada', 'Streep'),
    ('The Devil Wears Prada', 'Hathaway'),
    ('The Devil Wears Prada', 'Blunt'),
    ('The Wolf of Wall Street', 'DiCaprio'),
    ('The Wolf of Wall Street', 'Robbie'),
    ('The Wolf of Wall Street', 'Hill'),
    ('Goodfellas', 'De Niro'),
    ('Goodfellas', 'Liotta'),
    ('Goodfellas', 'Pesci'),
    ('Taxi Driver', 'De Niro'),
    ('Taxi Driver', 'Foster'),
    ('Paddington', 'Whishaw')
) AS v(titre, nom)
JOIN film f ON f.titre = v.titre
JOIN acteur a ON a.nom = v.nom;

INSERT INTO commentaire (auteur, date, message, film_id)
SELECT v.auteur, CAST(v.date AS DATE), v.message, f.id
FROM (VALUES
    ('Inception', 'Alice', '2024-03-10', 'Un chef-d''oeuvre'),
    ('Inception', 'Karim', '2024-05-18', 'La toupie tombe ou pas ?'),
    ('Inception', 'Léa', '2025-01-07', 'Hans Zimmer au sommet'),
    ('Intouchables', 'Bob', '2024-04-02', 'Très drôle et touchant'),
    ('Intouchables', 'Inès', '2024-09-21', 'Omar Sy est génial'),
    ('The Godfather', 'David', '2023-11-12', 'Un classique absolu'),
    ('The Godfather', 'Oscar', '2024-02-28', 'Un peu long mais culte'),
    ('Interstellar', 'Chloé', '2024-06-15', 'J''ai pleuré à la fin'),
    ('Interstellar', 'Mathis', '2024-08-03', 'Il faut le voir au cinéma'),
    ('Interstellar', 'Nora', '2025-02-11', 'Bande-son incroyable'),
    ('The Dark Knight', 'Hugo', '2023-12-01', 'Ledger est magistral'),
    ('The Dark Knight', 'Julie', '2024-07-19', 'Le meilleur Batman'),
    ('Oppenheimer', 'Farid', '2023-08-05', 'Murphy impressionnant'),
    ('Oppenheimer', 'Emma', '2023-09-14', 'Trop long à mon goût'),
    ('The Prestige', 'Gabriel', '2024-10-30', 'Quel twist final !'),
    ('Memento', 'Paul', '2024-01-22', 'Je n''ai rien compris'),
    ('Memento', 'Alice', '2024-01-25', 'À revoir pour comprendre'),
    ('Dunkirk', 'Oscar', '2024-04-17', 'Tendu du début à la fin'),
    ('Titanic', 'Inès', '2023-10-02', 'Il y avait de la place !'),
    ('Titanic', 'Chloé', '2024-02-14', 'Parfait pour la Saint-Valentin'),
    ('Pulp Fiction', 'Karim', '2024-03-30', 'Les dialogues sont cultes'),
    ('Forrest Gump', 'Julie', '2024-05-05', 'Cours Forrest, cours !'),
    ('The Matrix', 'Mathis', '2023-06-23', 'Pilule rouge, sans hésiter'),
    ('The Matrix', 'Hugo', '2024-11-11', 'Révolutionnaire en 1999'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'Léa', '2024-12-19', 'Une épopée magnifique'),
    ('Gladiator', 'David', '2024-06-20', 'Crowe est impérial'),
    ('Joker', 'Nora', '2024-10-09', 'Phoenix habité par le rôle'),
    ('Alien', 'Gabriel', '2024-10-31', 'Ça fait encore peur !'),
    ('Back to the Future', 'Paul', '2024-10-21', 'Un film culte'),
    ('Back to the Future', 'Emma', '2025-03-03', 'Parfait en famille'),
    ('The Silence of the Lambs', 'Farid', '2024-04-10', 'Hopkins glaçant'),
    ('Fight Club', 'Bob', '2024-11-10', 'On n''en parle pas'),
    ('Seven', 'Karim', '2024-01-31', 'Qu''y a-t-il dans la boîte ?'),
    ('La Haine', 'Inès', '2024-05-31', 'Toujours d''actualité'),
    ('Le Dîner de cons', 'Oscar', '2024-04-15', 'Villeret est génial'),
    ('Les Visiteurs', 'Julie', '2024-01-27', 'Okayyy !'),
    ('Léon', 'Chloé', '2024-09-14', 'Portman bluffante'),
    ('The Lion King', 'Emma', '2024-11-09', 'Hakuna Matata'),
    ('Toy Story', 'Paul', '2024-03-27', 'Vers l''infini et au-delà'),
    ('Le Voyage de Chihiro', 'Léa', '2024-04-10', 'Poétique et magique'),
    ('Avengers: Endgame', 'Hugo', '2024-04-24', 'Une fin épique'),
    ('Avengers: Endgame', 'Mathis', '2024-05-01', 'Trop de personnages'),
    ('Il était une fois dans l''Ouest', 'David', '2024-08-27', 'Musique de Morricone'),
    ('Mission: Impossible', 'Gabriel', '2024-10-30', 'La scène du câble !'),
    ('Top Gun: Maverick', 'Farid', '2024-05-25', 'Scènes aériennes folles'),
    ('Rocky', 'Bob', '2024-03-30', 'Motivant'),
    ('La La Land', 'Nora', '2024-01-25', 'Fin douce-amère'),
    ('Whiplash', 'Karim', '2024-12-24', 'Simmons terrifiant'),
    ('Jurassic Park', 'Julie', '2024-10-20', 'Les effets tiennent la route'),
    ('Star Wars: A New Hope', 'Mathis', '2024-05-04', 'Que la Force soit avec vous'),
    ('Parasite', 'Inès', '2024-06-05', 'Palme d''or méritée'),
    ('Dune', 'Léa', '2024-09-15', 'Visuellement bluffant'),
    ('Dune', 'Oscar', '2024-09-20', 'Vivement la suite'),
    ('The Shawshank Redemption', 'David', '2024-03-01', 'Mon film préféré'),
    ('Bienvenue chez les Ch''tis', 'Paul', '2024-02-27', 'Hilarant'),
    ('The Shining', 'Gabriel', '2024-10-16', 'Here''s Johnny !'),
    ('Bohemian Rhapsody', 'Chloé', '2024-10-31', 'Malek bluffant en Mercury'),
    ('The Wolf of Wall Street', 'Farid', '2024-12-25', 'DiCaprio en roue libre'),
    ('Goodfellas', 'Hugo', '2024-09-12', 'Scorsese au sommet'),
    ('Paddington', 'Emma', '2024-12-03', 'Adorable')
) AS v(titre, auteur, date, message)
JOIN film f ON f.titre = v.titre;
